export const ROLES = {
  SEKRETARIS_KANTOR: 'sekretaris-kantor',
  KETUA: 'ketua',
  SEKRETARIS_PENGURUS: 'sekretaris-pengurus',
  KABAG: 'kabag'
}

export const SURAT_MASUK_STATUS = {
  DITERIMA: 'DITERIMA',
  DIPROSES: 'DIPROSES',
  DISPOSISI_KETUA: 'DISPOSISI_KETUA',
  DISPOSISI_SEKPENGURUS: 'DISPOSISI_SEKPENGURUS',
  DISPOSISI_KABAG: 'DISPOSISI_KABAG',
  SELESAI: 'SELESAI'
}
